import { PaymentOptionType } from '@bp/shared/models/business';
import { CashierLanguage } from '@bp/shared/models/cashier';
import { Currency } from '@bp/shared/models/currencies';
import { IClientDetails } from './client-details';
import { CashierLaunchButtonMode, CashierTheme } from './enums';

export interface ICashierEmbeddedParameters extends IClientDetails {

	amount: string | null;

	amountLock: boolean | null;

	cashierKey: string | null;

	cashierToken: string | null;

	orderId: string | null;

	trackingId: string | null;

	affiliateId: string | null;

	platformId: string | null;

	ip: string | null;

	directPaymentMethod: PaymentOptionType | null;

	hideHeader: boolean | null;

	showFooter: boolean | null;

	currencyLock: boolean | null;

	showRedirectMessage: boolean | null;

	currency: Currency | null;

	/**
	 * If set generates a launch button instead of opening the cashier right on the spot
	 */
	buttonMode: CashierLaunchButtonMode | null;

	/**
	 * Text for the launch button generated by turning on one of the button modes
	 */
	buttonText: string | null;

	/**
	 * Text for the button inside the cashier which initiates a payment transaction
	 */
	depositButtonText: string | null;

	theme: CashierTheme | null;

	language: CashierLanguage | null;

	// not exposed to merchants

	onlyCreditCardPaymentMethod: boolean | null;

	/**
	 * Set by the cashier loader script when the launch button mode tab is activated
	 */
	backUrl: string | null;

	isDemostand: boolean | null;

}
