export default {
	cc: {
		expired: 'The expiration date provided is already expired'
	},
	ccAmount: 'The amount is invalid',
	ccCountry: 'The country not found',
	ccExpDate: 'The expiration date is invalid e.g.: MM/YY',
	ccHolder: 'The card holder name is incorrect. Should contain first name and last name',
	ccNumber: 'The credit card number is incorrect',
	ccVerificationCode: 'The CVV code is incorrect',
	digits: 'The value must contain only digits',
	email: 'Incorrect email address',
	letters: 'The value must not contain any special characters or digits',
	matDatepickerParse: 'The date is invalid',
	noZero: 'The value cannot be zero',
	maximum: 'The value must be less than or equal to {{required}}',
	maxlength: 'The value must be at most {{required}} characters',
	minimum: 'The value must be higher than or equal to {{required}}',
	minlength: 'The value must be at least {{required}} characters',
	pattern: 'The value is invalid',
	phoneParseError: 'The phone number is incorrect',
	phoneTooLong: 'The phone number is too long',
	phoneTooShort: 'The phone number is too short',
	required: 'You must enter a value',
	'required-address': 'Please enter your address',
	'required-amount': 'Please enter the amount',
	'required-city': 'Please enter your city',
	'required-country': 'Please select your country',
	'required-cvv': 'Please enter a CVV code',
	'required-default': 'You must enter a value',
	'required-email': 'Please enter your email address',
	'required-expiry': 'Expiration date is required e.g.: MM/YY',
	'required-holder': 'Please enter the card holder\'s name',
	'required-number': 'Please enter a credit card number',
	'required-phone': 'Please enter your phone number',
	'required-state': 'Please select your state',
	'required-zipCode': 'Please enter your zip code',
	stateCode: 'Such state doesn\'t exist',
	countryNotFound: 'Such country doesn\'t exist',
	autocompleteNotFound: 'There is no match on the list',
	minMoreThanOrEqualMax: 'The value must be less than the max value',
	maxLessThanOrEqualMin: 'The value must be greater than the min value',
	valueMoreThanMax: 'The value must be less than or equal to the max value',
	valueLessThanMin: 'The value must be greater than  or equal to the min value',
	passwordMinLength: 'The password has to contain at least 8 characters',
	passwordConfirm: 'Password confirmation doesn\'t match new password',
	password: 'Passwords must contain both uppercase and lowercase letters, a digit and a special character',
	ip: 'The entered IP address is not correct',
	url: 'The url is not correct, must start with http(s)://'
};
